### ISSUE TITLE
Question: why are there 2 versions of eco-index-audit on npmjs.com?

### ISSUE THREAD

**Issue by Lucas-C** [cnumr/ecoindex-audit#43]
* https://www.npmjs.com/package/eco-index-audit
* https://www.npmjs.com/package/@cnumr/eco-index-audit

Both NPM packages refer to the repository https://github.com/EmmanuelDemey/eco-index-audit (which is not this one)

It doesn't appear clearly that @EmmanuelDemey repo is a fork of this one (or the other way),
and there are recent contributions on both repositories by @EmmanuelDemey...

It's all a bit confusing 😅

**Comment by EmmanuelDemey** [comment]
Hi Lucas,

You are right. 

https://www.npmjs.com/package/eco-index-audit (https://github.com/EmmanuelDemey/eco-index-audit) was my module before moving it to the CNUMR organsation. 

Let me fix that.

**Comment by EmmanuelDemey** [comment]
Fixed. and deployed. 

Thanks @Lucas-C

**Comment by Lucas-C** [comment]
Thank you, it's much clearer now 👍
